//
//  PDFExportService.swift
//  LayLedger
//
//  Renders a real PDF report with UIGraphicsPDFRenderer (no dependencies).
//

import UIKit

struct ReportSummaryItem {
    let label: String
    let value: String
}

enum PDFExportService {

    static func generateReport(title: String,
                               subtitle: String,
                               summary: [ReportSummaryItem],
                               eggsByBreed: [BarDatum],
                               profitByMonth: [BarDatum]) -> URL? {
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter @ 72dpi
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("LayLedger-Report.pdf")

        let amber = UIColor(hex: "F59E0B")
        let teal = UIColor(hex: "0D9488")
        let ink = UIColor(hex: "422006")
        let sub = UIColor(hex: "78622C")

        do {
            try renderer.writePDF(to: url) { ctx in
                ctx.beginPage()
                var y: CGFloat = 48
                let left: CGFloat = 48
                let contentWidth = pageRect.width - left * 2

                // Header band
                let band = CGRect(x: left, y: y, width: contentWidth, height: 64)
                let bandPath = UIBezierPath(roundedRect: band, cornerRadius: 14)
                amber.withAlphaComponent(0.15).setFill()
                bandPath.fill()
                draw(text: title, at: CGPoint(x: left + 18, y: y + 12),
                     font: .systemFont(ofSize: 24, weight: .bold), color: ink)
                draw(text: subtitle, at: CGPoint(x: left + 18, y: y + 40),
                     font: .systemFont(ofSize: 12, weight: .medium), color: sub)
                y += 88

                // Summary grid
                draw(text: "Summary", at: CGPoint(x: left, y: y),
                     font: .systemFont(ofSize: 16, weight: .bold), color: ink)
                y += 26
                let colW = contentWidth / 2
                for (index, item) in summary.enumerated() {
                    let col = index % 2
                    let row = index / 2
                    let x = left + CGFloat(col) * colW
                    let cy = y + CGFloat(row) * 46
                    draw(text: item.value, at: CGPoint(x: x, y: cy),
                         font: .systemFont(ofSize: 20, weight: .bold), color: amber)
                    draw(text: item.label, at: CGPoint(x: x, y: cy + 26),
                         font: .systemFont(ofSize: 11, weight: .regular), color: sub)
                }
                let rows = (summary.count + 1) / 2
                y += CGFloat(rows) * 46 + 24

                // Eggs by breed bars
                y = drawBarSection(title: "Eggs by breed (last 7 days)", bars: eggsByBreed,
                                   color: amber, ink: ink, sub: sub, left: left, width: contentWidth, top: y)
                y += 24

                // Profit by month bars (signed)
                y = drawBarSection(title: "Profit by month", bars: profitByMonth,
                                   color: teal, ink: ink, sub: sub, left: left, width: contentWidth, top: y)

                // Footer
                draw(text: "Generated by Lay Ledger • \(mediumDate(Date()))",
                     at: CGPoint(x: left, y: pageRect.height - 48),
                     font: .systemFont(ofSize: 10, weight: .regular), color: sub)
            }
            return url
        } catch {
            return nil
        }
    }

    private static func drawBarSection(title: String, bars: [BarDatum], color: UIColor,
                                       ink: UIColor, sub: UIColor,
                                       left: CGFloat, width: CGFloat, top: CGFloat) -> CGFloat {
        var y = top
        draw(text: title, at: CGPoint(x: left, y: y),
             font: .systemFont(ofSize: 16, weight: .bold), color: ink)
        y += 28
        let chartHeight: CGFloat = 130
        let maxV = max(bars.map { abs($0.value) }.max() ?? 1, 1)
        let count = max(bars.count, 1)
        let slot = width / CGFloat(count)
        let barW = min(slot * 0.55, 46)
        let baseY = y + chartHeight

        // baseline
        let baseline = UIBezierPath()
        baseline.move(to: CGPoint(x: left, y: baseY))
        baseline.addLine(to: CGPoint(x: left + width, y: baseY))
        sub.withAlphaComponent(0.4).setStroke()
        baseline.lineWidth = 1
        baseline.stroke()

        for (index, bar) in bars.enumerated() {
            let cx = left + slot * CGFloat(index) + slot / 2
            let h = CGFloat(abs(bar.value) / maxV) * (chartHeight - 8)
            let rect = CGRect(x: cx - barW / 2, y: baseY - h, width: barW, height: h)
            let path = UIBezierPath(roundedRect: rect, cornerRadius: 5)
            (bar.value < 0 ? UIColor(hex: "EF4444") : color).setFill()
            path.fill()
            draw(text: bar.label, at: CGPoint(x: cx - barW / 2 - 4, y: baseY + 6),
                 font: .systemFont(ofSize: 9, weight: .medium), color: sub, width: barW + 16, center: true)
        }
        return baseY + 28
    }

    private static func draw(text: String, at point: CGPoint, font: UIFont, color: UIColor,
                             width: CGFloat = 480, center: Bool = false) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = center ? .center : .left
        paragraph.lineBreakMode = .byTruncatingTail
        let attrs: [NSAttributedString.Key: Any] = [
            .font: font, .foregroundColor: color, .paragraphStyle: paragraph
        ]
        let rect = CGRect(x: point.x, y: point.y, width: width, height: font.lineHeight + 4)
        text.draw(in: rect, withAttributes: attrs)
    }
}
